PINK = "#e2979c"
RED = "#e7305b"
GREEN = "#9bdeac"
GREEN_2 = "#00712D"
GREEN_REST = "#83d0c9"
BLUE = "#98c1d9"
ORANGE = "#ffcc5c"
YELLOW = "#F3FEB8"
FONT_NAME = "Courier"
WHITE = "#fff5ee"
GOLD = "#FFD700"
PURPLE = "#A020F0"

WORK_COLOR = ORANGE
REST_COLOR = GREEN_REST
LONG_REST_COLOR = BLUE
WORK_TEXT_COLOR = RED
TEXT_COLOR = WHITE